uint8 PLAN=1
uint8 EXECUTE=2
uint8 GO=3
uint8 CARTESIAN_COMPUTE=4
uint8 ABORT=255
uint8 action_type

# Goal pose
geometry_msgs/PoseStamped goal

# Goal as a named target
string named_target

# Goal as Cartesian wayposes
geometry_msgs/Pose[] cartesian_wayposes
string cartesian_frame


# Tolerances for target position, orientation, and joint values
float32 tolerance_posit
float32 tolerance_orien
# float32 tolerance_joint
---
# Fraction of successfully computed Cartesian path
float32 cartesian_fraction